# Site wide configuration
source: src/
destination: src/_site

title: "Jekyll Gulp boilerplate"
description: >
  "Jekyll Gulp boilerplate based on Bulma"
logo: "/assets/images/icon.png"
keywords:
  - keyword
  - another
  - important
  - keyword

url: "https://your-website.com"
canonical_url: *url

google_analytics: "UA-..."

# Jekyll configuration
permalink: pretty
lsi: false
future: true
show_drafts: false
markdown: kramdown
kramdown:
  toc_levels: 1..3
  input: GFM
  hard_wrap: false
  auto_ids: true
  entity_output: as_char
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
highlighter: rouge
strict_front_matter: true
keep_files:
  - .git
include:
  - .htaccess
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules
  - vendor
  - _assets
  - _scripts
  - gulpfile.js
  - paths.js
  - Rakefile
  - icon.png
  - LICENSE
  - README.md

# Collections
collections:
  faqs:
    output: true
    permalink: /:collection/:path/
    title: FAQs

# Front Matter Defaults
defaults:
  # All
  - scope:
      path: ""
    values:
      image: /assets/images/default-card.png # default image for open graph (jekyll-seo-tag)
  # Posts
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      breadcrumbs:
        - label: "Blog Articles"
          url: /articles/
      widgets:
        search: true
        categories: true
        tags: true
        related: true
        archives: true
      image: /assets/images/default.png
  # FAQs
  - scope:
      path: _faqs
      type: faqs
    values:
      layout: page
      read_time: true
      breadcrumbs:
        - label: "Frequently Asked Questions"
          url: /faqs/
  # Pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: page

# Plugins
plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-algolia
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - amp-jekyll

# Plugin : AMP (amp-jekyll)
ampdir: amp

# Plugin: SEO (jekyll-seo-tag)
webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234
  baidu: 1234

social: # https://developers.google.com/search/docs/data-types/social-profile
  name: Shiqan
  links:
    - https://twitter.com/...
    - https://www.facebook.com/...
    - https://www.linkedin.com/...
    - https://github.com/Shiqan

author:
  name: "Shiqan"
  uri: &uri "https://your-website.com/about/"
  url: *uri
  bio: "Just a short description here..."
  picture: "/assets/images/profile-picture.jpg"
  twitter: "https://twitter.com/..."
  facebook: "https://www.facebook.com/..."
  instagram: "https://www.instagram.com/.../"
  github: "https://github.com/Shiqan"

# Plugin: Pagination (jekyll-paginate-v2)
pagination:
  enabled: true
  debug: false
  per_page: 5
  permalink: "/page/:num/"
  title: ":title - Page :num of :max"
  limit: 0
  sort_field: "date"
  sort_reverse: true

# Plugin: Auto Pages (jekyll-paginate-v2)
autopages:
  enabled: true
  categories:
    enabled: true
    slugify:
      mode: raw
      cased: true
    layouts:
      - "archive.html"
    title: ":cat"
    permalink: "/category/:cat"
  collections:
    enabled: false
  tags:
    enabled: true
    slugify:
      mode: raw
      cased: true
    layouts:
      - "archive.html"
    title: ":tag"
    permalink: "/tag/:tag"

# Plugin: Archives (jekyll-archives)
jekyll-archives:
  enabled:
    - year
  layout: "archive"
  permalinks:
    year: "/archive/:year/"

# Plugin: Jekyll Algolia
algolia:
  vars: ["title", "excerpt", "date", "url", "categories", "tags"]
  application_id: 0OO1N7335I
  index_name: shiqan
  search_only_api_key: f39b241334abe22209841acb04a12f52
  nodes_to_index: "p"
  files_to_exclude:
    - index.html
    - index.md
    - _pages/404.md
    - _pages/articles.md
    - _pages/faqs.md
    - _pages/sitemap.md
    - _pages/tag.md
